name: Sync with restic by tag
on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Bump version and test
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out code
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Test local
        id: test_local
        run: ./test.sh local

      - name: Test S3
        id: test_s3
        run: ./test.sh s3

      - name: Build and push
        run: |
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag "ghcr.io/reddec/auto-restic:${GITHUB_REF_NAME}" .

      - name: Create release
        run: |
          gh release create "${GITHUB_REF_NAME}" --notes "* use restic version: ${GITHUB_REF_NAME}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}